## Step 6: Most common expressions

```{r }
library(tidyverse)

df5 <- df4b_acima_1988_minus_classes_cont_ementa|>
  filter(!str_detect(Incidente_3, "AgR"))|>
  filter(!str_detect(Incidente_3, "RG"))|>
  filter(!str_detect(Incidente_3, "SL"))|>
  filter(Incidente_3 %in% c("","Acordo", "Acordo-segundo", "ED-terceiros-ED-ED", "TA-Ref", "MC", "ADPF"))


peter_pan <- df5 |>
  filter(Motivo=="penal")|>
  select(Ementa)


packages <- c("wordcloud", "tm")

lapply(packages, require , character.only = TRUE)

peter_text <- Corpus(VectorSource(peter_pan))

peter_text_clean <- tm_map(peter_text, removePunctuation)

peter_text_clean <- tm_map(peter_text_clean, content_transformer(tolower))

peter_text_clean <- tm_map(peter_text_clean, removeNumbers)

peter_text_clean <- tm_map(peter_text_clean, stripWhitespace)


peter_text_clean <- tm_map(peter_text_clean, removeWords, stopwords('portuguese'))

wordcloud(peter_text_clean, scale = c(2, 1), min.freq = 50, colors = rainbow(30))
```

```{r }

library(dplyr)
library(tidytext)
library(ggplot2)

peter_pan <- df5 |>
  filter(Motivo=="penal")|>
  select(Ementa)


head(peter_pan, n = 20)

peter_pan_df <- tibble(Text = peter_pan) # tibble aka neater data frame

peter_words <- peter_pan_df %>% 
   mutate(across(everything(), ~as.character(.))) %>% 
                  unnest_tokens(output = word, input = Text) 

peter_words <- peter_words %>%
                   anti_join(stop_words) # Remove stop words in peter_words

peter_wordcounts <- peter_words %>% count(word, sort = TRUE)

head(peter_wordcounts)

peter_wordcounts %>% 
  filter(n > 70000) %>% 
  mutate(word = reorder(word, n)) %>% 
    ggplot(aes(word, n)) + 
    geom_col() +
    coord_flip() +
    labs(x = "Word \n", y = "\n Count ", title = "Frequent Words In Peter Pan \n") +
    geom_text(aes(label = n), hjust = 1.2, colour = "white", fontface = "bold") +
    theme(plot.title = element_text(hjust = 0.5), 
        axis.title.x = element_text(face="bold", colour="darkblue", size = 12),
        axis.title.y = element_text(face="bold", colour="darkblue", size = 12))
```
